name: Build and Test Docker

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker Image
        run: docker build -t custom-arachni .

      - name: Test Arachni Image
        run: docker run --rm custom-arachni arachni http://example.com
