name: Build and Test Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code (actualizado a v3)
    - name: Check out the repository
      uses: actions/checkout@v3  # Actualiza a la versión más reciente

    - name: Remove conflicting package
      run: sudo apt-get remove -y containerd
    
    - name: Update package lists
      run: sudo apt-get update
    
    - name: Install containerd.io
      run: sudo apt-get install -y containerd.io

    - name: Clear Held Packages
      run: sudo apt-get --fix-broken install
  
    # 2. Set up Docker
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose

    # 3. Build Docker Image
    - name: Build Docker Image
      run: docker build -t custom-arachni .
