name: Build and Test Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code (actualizado a v3)
    - name: Check out the repository
      uses: actions/checkout@v3  # Actualiza a la versión más reciente

    # 2. Set up Docker
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose

    # 3. Build Docker Image
    - name: Build Docker Image
      run: docker build -t custom-arachni .

