name: Docker Inspection

on:
  workflow_dispatch: # Permite ejecutar este flujo manualmente desde GitHub

jobs:
  docker-inspect:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Ejecutar el contenedor en segundo plano
      - name: Run Arachni Docker Container
        run: |
          docker run -d --name arachni_temp_container \
            -v $(pwd)/output:/output \
            arachni/arachni \
            /usr/local/arachni/bin/arachni https://cybermusik.onrender.com/

      # Paso 3: Esperar para inspeccionar manualmente o procesar datos

      # Paso 4: Subir la carpeta output como artifact para descargarla
      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: arachni-output
          path: ./output
