name: Security Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p output

      - name: Run Arachni scan
        run: |
          docker run --rm -v $(pwd)/output:/output arachni/arachni \
            /usr/local/arachni/bin/arachni https://cybermusik.onrender.com/views/logins/login.html \
            --output-file=/output/arachni-report.afr

      - name: Check output after Arachni scan
        run: ls -la ./output

      - name: Convert Arachni report to HTML
        run: |
          docker run --rm -v $(pwd)/output:/output arachni/arachni \
            /usr/local/arachni/bin/arachni_reporter /output/arachni-report.afr \
            --reporter=html:output=/output

      - name: Check output after conversion
        run: ls -la ./output

      - name: Rename HTML report
        run: mv ./output/*.html.zip ./output/arachni-report.html.zip

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: arachni-report
          path: ./output/arachni-report.html.zip
