name: Security Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        node-version: '20.17.0'

    - name: Install Arachni
      run: sudo apt-get install -y arachni

    - name: Build Arachni Docker Image
      run: |
        docker build -t custom-arachni .  # Build your custom Arachni image from the Dockerfile

    - name: Run Arachni Fuzzing
      run: |
        # Run Arachni fuzzing on the /d/users/sign_in endpoint of the web service
        docker run --rm -v $(pwd):/output custom-arachni /opt/arachni/bin/arachni http://arachni:9292/d/users/sign_in --output /output/arachni-report.afr

    - name: Convert Report to HTML
      run: |
        docker run --rm -v $(pwd):/output custom-arachni /opt/arachni/bin/arachni_reporter /output/arachni-report.afr --reporter=html:output=/output/arachni-report.html

    - name: Upload scan report
      uses: actions/upload-artifact@v3
      with:
        name: arachni-report
        path: arachni-report.afr

    - name: Validate Scan Results
      run: |
        if grep -q "High" /output/arachni-report.html; then
          echo "Critical vulnerabilities detected!"
          exit 1
        else
          echo "No critical vulnerabilities detected."
        fi
