name: Security Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p output

      - name: Run Arachni scan
        run: |
          docker run --rm -v $(pwd)/output:/output arachni/arachni https://cybermusik.onrender.com/ --report-save-path=/output/arachni-report.afr

      - name: Convert Arachni report to HTML
        run: |
          docker run --rm -v $(pwd)/output:/output arachni/arachni /usr/local/arachni/bin/arachni_reporter /output/arachni-report.afr --reporter=html:output=/output/report.html.zip

      - name: List output files
        run: ls -l ./output

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: arachni-report
          path: ./output/report.html.zip
