name: Security Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      with:
        version: 'latest'

    - name: Build custom Arachni Docker image
      run: |
        docker build -t custom-arachni .

    - name: Run Arachni Fuzzing
      run: |
        # Ensure the Arachni Docker image is pulled
        docker pull arachni/arachni
        # Run Arachni fuzzing on the /d/users/sign_in endpoint of the web service
        docker run --rm -v $(pwd):/output custom-arachni http://web:9292/d/users/sign_in --output /output/arachni-report.afr

    - name: Upload scan report
      uses: actions/upload-artifact@v3
      with:
        name: arachni-report
        path: ./arachni-report.afr
<<<<<<< HEAD
=======

    - name: Fail if vulnerabilities found
      run: |
        if [ -s ./arachni-report.afr ]; then
          echo "Security issues detected! Please check the Arachni report."
          exit 1
        else
          echo "No security issues detected."
        fi
>>>>>>> f171b7483e412797b264f29e199e620dec443fae
