name: Security Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Prepare output directory
      run: mkdir -p output

    - name: Run Arachni Fuzzing
      run: |
        docker run --rm -v ${{ github.workspace }}/output:/output arachni/arachni /usr/local/arachni/bin/arachni http://arachni:9292/d/users/sign_in --report-save-path=/output/arachni-report.afr

    - name: Convert Report to HTML
      run: |
        docker run --rm -v ${{ github.workspace }}/output:/output arachni/arachni /usr/local/arachni/bin/arachni_reporter /output/arachni-report.afr --reporter=html:output=/output

    - name: List files in output
      run: ls -l ./output

    - name: Unzip HTML report
      run: |
        # Encuentra y descomprime el archivo .zip generado
        unzip "./output/*.html.zip" -d ./output

    - name: List files after unzip
      run: ls -l ./output

    - name: Upload scan report
      uses: actions/upload-artifact@v3
      with:
        name: arachni-report
        path: ./output/*.html

    - name: Validate Scan Results
      run: |
        # Busca vulnerabilidades críticas en el reporte descomprimido
        if grep -q "High" ./output/*.html; then
          echo "Critical vulnerabilities detected!"
          exit 1
        else
          echo "No critical vulnerabilities detected."
        fi
