name: Security Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p output

      - name: Run Arachni scan
        run: |
          docker run --rm -v $(pwd)/output:/output arachni/arachni \
            /usr/local/arachni/bin/arachni https://cybermusik.onrender.com/views/logins/login.html \
            --report-save-path=/output/arachni-report.html

      - name: List Output Files
        run: |
          echo "Files in output directory:"
          ls -la ./output

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: arachni-report
          path: ./output/arachni-report.html
