name: Security Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Run Arachni Fuzzing
      run: |
        docker run --rm -v $(pwd):/output arachni/arachni /usr/local/arachni/bin/arachni http://arachni:9292/d/users/sign_in --report-save-path=/output/arachni-report.afr

    - name: Convert Report to HTML
      run: |
        docker run --rm -v $(pwd):/output arachni/arachni /usr/local/arachni/bin/arachni_reporter /output/arachni-report.afr --reporter=html:output=/output/arachni-report.html

    - name: Upload scan report
      uses: actions/upload-artifact@v3
      with:
        name: arachni-report
        path: arachni-report.html

    - name: Validate Scan Results
      run: |
        if grep -q "High" /output/arachni-report.html; then
          echo "Critical vulnerabilities detected!"
          exit 1
        else
          echo "No critical vulnerabilities detected."
        fi
