name: TruffleHog Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install TruffleHog
        run: pip install trufflehog

      - name: Run TruffleHog to scan for secrets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          trufflehog --json https://github.com/EmilianoArroyo/ProyectoDeWeb

